version: "3.8"

services:
  localstack:
    image: localstack/localstack
    network_mode: bridge
    ports:
      - 4566:4566
      - 4571:4571
      - 8080:8080
    # environment:
    #   SERVICES: apigateway,cloudformation,iam,lambda,route53,s3
    #   DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
